FROM balenalib/raspberrypi4-64-alpine-golang:1.15-3.14-run

WORKDIR /opt/nexus

COPY ./ /opt/nexus

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
        make gcc musl-dev\
    && make service \
    && make service install \
    && mkdir -p /run/nexus/ \
    && apk del --no-network .build-deps
